############################################
# Fill in the missing code below
############################################

# The public key generated by the azapi_resource_action resource
# Set sensitive to true to hide the value in the output
output "key_data" {

}

# The private key generated by the azapi_resource_action resource
# Set sensitive to true to hide the value in the output
output "private_key_data" {

}

# Public IP of the Load Balancer
output "lb_public_ip" {

}

# App Code using the local variable from the module
output "app_code" {

}